/** The scrapbook as a Markdown file: everything, in reading order. */
import { placeOf } from "./data";
import { calcMoney, workFromMoney } from "./money";
import type { Project } from "./types";
import { arr, niceDate, obj, safeUrl, str, today } from "./util";

export function toMarkdown(p: Project, mode?: "founding"): string {
  const b = p.book!; const cur = str(obj(b.money).currency) || p.currency;
  const steps = arr(obj(b.path).steps); const pitch = obj(b.pitch), br = obj(b.brand), l = obj(b.legal), t = obj(b.tools), v = obj(b.vision);
  const w = p.work ?? workFromMoney(b.money); const c = calcMoney(w);
  const line = (s: unknown) => str(s).replace(/\s+/g, " ").trim();
  const doneFor = (ref: string) => { const ss = steps.filter((s) => str(s.ref) === ref); return ss.length > 0 && ss.every((s) => p.done[str(s.id)]); };
  let md = `# ${line(b.name)}\n\n*${line(b.oneLiner)}*\n\nMade with Tada · ${placeOf(p)} · ${niceDate(p.builtAt || p.createdAt)}\n\n> The idea, in my words: ${line(p.idea)}\n\n`;
  if (mode === "founding") md += `## Founding page\n\n${line(b.name)} exists as of ${niceDate(today())}.\n\n${steps.map((s) => `- [x] ${line(s.title)} — ${niceDate(p.doneAt[str(s.id)] || today())}`).join("\n")}\n\n`;
  md += `## The dream\n\n${line(v.manifesto)}\n\n${v.why ? `*${line(v.why)}*\n\n` : ""}${v.dayInTheLife ? `**A day in the life, one year in.** ${line(v.dayInTheLife)}\n\n` : ""}${arr(v.milestones).length ? `Milestones: ${arr(v.milestones).map((m) => `${line(obj(m).title)} (${line(obj(m).when)})`).join("; ")}\n\n` : ""}`;
  if (arr(b.assumptions).length) md += `## Things Tada assumed\n\n${arr(b.assumptions).map((a) => `- ${line(a.text)}${a.because ? ` — because ${line(a.because)}` : ""}`).join("\n")}\n\n`;
  md += `## The pitch\n\n` + [["The problem", pitch.problem], ["The solution", pitch.solution], ["Who it's for", pitch.who], ["Why now", pitch.whyNow], ["How it makes money", pitch.howItMakesMoney], ["The first 90 days", pitch.first90Days], ["What could go wrong", pitch.risks]].map((s) => `**${s[0]}.** ${line(s[1])}`).join("\n\n") + "\n\n";
  md += `## Brand\n\nTagline: “${line(br.tagline)}”\n\nVoice: ${line(br.voice)}\n\nNames: ${arr(br.names).map((n) => `${line(obj(n).name)} (${line(obj(n).why)})`).join("; ")}\n\nPalette: ${arr(br.palette).map((x) => `${line(obj(x).name)} ${line(obj(x).hex)}`).join(", ")}\n\n${v.firstPost ? `First post: ${line(v.firstPost)}\n\n` : ""}`;
  md += `## Money workbook (${cur})\n\n**What I sell**\n\n${w.items.map((x) => `- ${x.item}: price ${x.price}, cost each ${x.unitCost}, ${x.units} a month`).join("\n")}\n\n**Fixed costs a month**\n\n${w.running.map((x) => `- ${x.item}: ${x.amount}`).join("\n")}\n\n**To start**\n\n${w.startup.map((x) => `- ${x.item}: ${x.low}–${x.high}`).join("\n")}\n\nStarting cash: ${w.cash} · ramp: ${w.ramp} months\n\n` + (c.ok ? `Contribution a month: ${Math.round(c.monthly)} · fixed: ${Math.round(c.fixed)} · profit at full volume: ${Math.round(c.profit)} · break-even: ${c.factor === Infinity ? "n/a" : Math.round(c.factor * 100) + "% of planned sales"} · cash-positive: ${c.positiveMonth ? "month " + c.positiveMonth : "not in year 1"} · lowest cash point: ${Math.round(c.low.v)}\n\nCash by month: ${c.months.map((x) => Math.round(x)).join(", ")}\n\n` : "") + (obj(b.leaner).title ? `**Start smaller:** ${line(obj(b.leaner).title)} — ${line(obj(b.leaner).whatChanges)}\n\n` : "") + (arr(b.funding).length ? `**Funding options**\n\n${arr(b.funding).map((f) => `- ${line(obj(f).name)} (${line(obj(f).type)}, ${line(obj(f).body)}): ${line(obj(f).fits)} ${line(obj(f).amount)} ${safeUrl(obj(f).url)}${obj(f).verify ? " — verify" : ""}`).join("\n")}\n\n` : "");
  md += `## Legal & licences — ${placeOf(p)}\n\n${line(l.summary)}\n\n*Not legal advice. Confirm every item with the official body before filing.*${b.verifiedAt ? ` Last checked against the web on ${niceDate(b.verifiedAt)}.` : ""}\n\n**Structure options**\n\n${arr(l.structures).map((s) => `- ${line(s.name)}${obj(s).recommended ? " (recommended to start)" : ""}: ${line(s.summary)} Cost: ${line(s.cost)}. Time: ${line(s.time)}.`).join("\n")}\n\n**Licence list**\n\n${arr(l.items).map((i) => `- [${doneFor(str(i.id)) ? "x" : " "}] **${line(i.title)}** (${line(i.status)}${i.verify ? ", verify" : ""}${obj(i.verified).status ? `, ${obj(i.verified).status}` : ""}) — ${line(i.why)} Issued by ${line(i.body)}. ${line(i.cost)} · ${line(i.time)}. ${safeUrl(i.url)}${obj(i.verified).note ? ` Note: ${line(obj(i.verified).note)}` : ""}`).join("\n")}\n\n`;
  md += `## Tools & vendors\n\n${arr(t.needs).map((n) => `**${line(n.need)}** — ${line(n.why)}\n\n${arr(n.options).map((o) => `- ${obj(o).recommended ? "★ " : ""}${line(o.name)} (${line(o.priceTier)} cost, convenience ${o.convenience}/5): ${line(o.note)} ${safeUrl(o.url)}`).join("\n")}`).join("\n\n")}\n\n`;
  md += `## The path to Ta-da\n\n${line(obj(b.path).target)}\n\n` + ["Decide", "Register", "Set up", "Launch"].map((ph) => `**${ph}**\n\n${steps.filter((s) => str(s.phase) === ph).map((s) => `- [${p.done[str(s.id)] ? "x" : " "}] ${line(s.title)} — ${[line(s.cost), line(s.time)].filter(Boolean).join(", ")}. ${line(s.detail)}${safeUrl(s.url) ? ` ${safeUrl(s.url)}` : ""}`).join("\n")}`).join("\n\n") + "\n";
  if (arr(p.facts).length) md += `\n## Conversation notes\n\n${arr(p.facts).map((f) => `- ${line(f)}`).join("\n")}\n`;
  return md;
}
